# Generated by Django 3.1.2 on 2020-10-09 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_auto_20201009_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlistentry',
            options={'verbose_name_plural': 'Waitlist Entries'},
        ),
    ]
