# Generated by Django 3.1.2 on 2020-10-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0003_auto_20201009_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='level',
            field=models.IntegerField(default=2, verbose_name='Class Leve'),
            preserve_default=False,
        ),
    ]
