# Generated by Django 3.1.2 on 2020-10-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('lecturer_name', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateField()),
                ('duration', models.IntegerField(help_text='Enter number of hours')),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
