# Generated by Django 3.1.2 on 2020-10-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='is_required',
            new_name='required',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='first_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='last_name',
        ),
        migrations.AddField(
            model_name='lecture',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')], default=1),
        ),
        migrations.AddField(
            model_name='lecture',
            name='slides_url',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TextField(),
        ),
    ]
